export type StaticProduct = {
  id: string
  name: string
  description: string
  price: number
  originalUrl: string
  imageUrl: string
  sourceShop: string
  rating: number
  genderFit: string[]
  ageRange: string[]
  interestTags: string[]
  styleFit: string[]
  occasionFit: string[]
  giftType: string
  isPersonalizable: boolean
  isLocal: boolean
  popularityScore: number
  isPremium: boolean
  inStock: boolean
  categories: string[]
}

export const PRODUCTS: StaticProduct[] = [
  // ── TECH & GADGETY ──
  { id:"p01", name:"Chytrý náramek Xiaomi Band 8", description:"Fitness tracker s AMOLED displejem, měření tepu a SpO2. Výdrž baterie 16 dní.", price:890, originalUrl:"https://www.mall.cz/chytre-naramky/xiaomi-band-8", imageUrl:"/products/p01.svg", sourceShop:"Mall.cz", rating:4.7, genderFit:["male","female"], ageRange:["teen","young_adult","adult"], interestTags:["tech","sport"], styleFit:["practical","adventurous"], occasionFit:["birthday","christmas"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:95, isPremium:false, inStock:true, categories:["tech"] },
  { id:"p02", name:"Bezdrátová sluchátka JBL Tune 520BT", description:"Bluetooth sluchátka s 57h výdrží baterie a Pure Bass zvukem.", price:1290, originalUrl:"https://www.mall.cz/sluchatka/jbl-tune-520bt", imageUrl:"/products/p02.svg", sourceShop:"Mall.cz", rating:4.5, genderFit:["male","female"], ageRange:["teen","young_adult","adult"], interestTags:["tech","games"], styleFit:["practical","comfort"], occasionFit:["birthday","christmas","just_because"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:92, isPremium:false, inStock:true, categories:["tech"] },
  { id:"p03", name:"Kindle Paperwhite 16GB", description:"E-čtečka s 6.8\" displejem, voděodolná, teplé podsvícení.", price:3490, originalUrl:"https://www.mall.cz/ctecky-knih/kindle-paperwhite", imageUrl:"/products/p03.svg", sourceShop:"Mall.cz", rating:4.9, genderFit:["male","female"], ageRange:["young_adult","adult","senior"], interestTags:["tech","books"], styleFit:["intellectual","comfort"], occasionFit:["birthday","christmas","graduation"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:98, isPremium:false, inStock:true, categories:["tech"] },
  { id:"p04", name:"Polaroid Go Gen 2 — instantní fotoaparát", description:"Nejmenší analogový instantní fotoaparát na světě. Dvojitá expozice, selfie zrcátko.", price:2490, originalUrl:"https://www.mall.cz/instantni-fotoaparaty/polaroid-go-gen2", imageUrl:"/products/p04.svg", sourceShop:"Mall.cz", rating:4.6, genderFit:["female","male"], ageRange:["teen","young_adult","adult"], interestTags:["tech","crafts","experiences"], styleFit:["aesthetic","adventurous"], occasionFit:["birthday","christmas","graduation","just_because"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:90, isPremium:false, inStock:true, categories:["tech"] },

  // ── KOSMETIKA & WELLNESS ──
  { id:"p05", name:"Sada pro vousáče Byjome Gentleman", description:"Olej na vousy, balzám a vosk v dárkové kazetě. Česká přírodní kosmetika.", price:1385, originalUrl:"https://www.darek.cz/darky-pro-muze/byjome-gentleman", imageUrl:"/products/p05.svg", sourceShop:"Darek.cz", rating:5.0, genderFit:["male"], ageRange:["young_adult","adult"], interestTags:["fashion","wellness"], styleFit:["aesthetic","practical"], occasionFit:["birthday","christmas","valentine"], giftType:"physical", isPersonalizable:false, isLocal:true, popularityScore:100, isPremium:false, inStock:true, categories:["wellness"] },
  { id:"p06", name:"Bohemia Přírodní kosmetika Levandule", description:"Dárková sada sprchový gel, šampon a mýdlo s levandulí. Ruční výroba.", price:395, originalUrl:"https://www.darek.cz/bohemia-levandule", imageUrl:"/products/p06.svg", sourceShop:"Darek.cz", rating:4.7, genderFit:["female","male"], ageRange:["young_adult","adult","senior","elderly"], interestTags:["wellness","fashion"], styleFit:["comfort","aesthetic"], occasionFit:["birthday","christmas","mothers_day","just_because"], giftType:"physical", isPersonalizable:false, isLocal:true, popularityScore:94, isPremium:false, inStock:true, categories:["wellness"] },
  { id:"p07", name:"Masážní pistole Therabody Mini", description:"Kompaktní masážní přístroj se 3 nástavci. Ideální po tréninku i do kanceláře.", price:3990, originalUrl:"https://www.mall.cz/masazni-pristroje/therabody-mini", imageUrl:"/products/p07.svg", sourceShop:"Mall.cz", rating:4.8, genderFit:["male","female"], ageRange:["young_adult","adult","senior"], interestTags:["wellness","sport"], styleFit:["practical","comfort"], occasionFit:["birthday","christmas","just_because"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:93, isPremium:false, inStock:true, categories:["wellness"] },
  { id:"p08", name:"Dárková sada pro maminku — 6 dárků", description:"Svíčka, krém na ruce, čaj, čokoláda, ponožky a gratulace v krabici.", price:895, originalUrl:"https://www.darek.cz/sada-pro-maminku", imageUrl:"/products/p08.svg", sourceShop:"Darek.cz", rating:4.8, genderFit:["female"], ageRange:["adult","senior","elderly"], interestTags:["wellness","home"], styleFit:["comfort","practical"], occasionFit:["birthday","christmas","mothers_day"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:96, isPremium:false, inStock:true, categories:["wellness"] },

  // ── JÍDLO & PITÍ ──
  { id:"p09", name:"Balíček pivních specialit z celého světa", description:"12 piv z 8 zemí v dárkové krabici. Belgie, Německo, Anglie, Česko a další.", price:785, originalUrl:"https://www.darek.cz/balik-pivnich-specialit", imageUrl:"/products/p09.svg", sourceShop:"Darek.cz", rating:4.8, genderFit:["male","female"], ageRange:["young_adult","adult","senior"], interestTags:["food"], styleFit:["comfort","adventurous"], occasionFit:["birthday","christmas","just_because"], giftType:"physical", isPersonalizable:false, isLocal:true, popularityScore:96, isPremium:false, inStock:true, categories:["food"] },
  { id:"p10", name:"Čajová kolekce Aroma Exclusive", description:"Luxusní dárkové balení 6 druhů sypaného čaje v plechových dózách.", price:475, originalUrl:"https://www.darek.cz/aroma-exclusive", imageUrl:"/products/p10.svg", sourceShop:"Darek.cz", rating:5.0, genderFit:["female","male"], ageRange:["young_adult","adult","senior","elderly"], interestTags:["food","wellness"], styleFit:["aesthetic","comfort","intellectual"], occasionFit:["birthday","christmas","mothers_day","just_because"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:100, isPremium:false, inStock:true, categories:["food"] },
  { id:"p11", name:"Degustační set single malt whisky — 5×50ml", description:"Pět skotských single maltů v dárkové kazetě. Oblasti Speyside, Islay, Highland.", price:1890, originalUrl:"https://www.mall.cz/whisky/degustacni-set-single-malt", imageUrl:"/products/p11.svg", sourceShop:"Mall.cz", rating:4.9, genderFit:["male","female"], ageRange:["adult","senior"], interestTags:["food","premium"], styleFit:["intellectual","aesthetic"], occasionFit:["birthday","christmas","valentine","graduation"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:97, isPremium:false, inStock:true, categories:["food"] },
  { id:"p12", name:"Keramické servírovací misky FOOD Balvi", description:"Set 3 misek ve tvaru nápisů FOOD. Design z Barcelony.", price:490, originalUrl:"https://www.darek.cz/servirovaci-misky", imageUrl:"/products/p12.svg", sourceShop:"Darek.cz", rating:4.7, genderFit:["female","male"], ageRange:["young_adult","adult","senior"], interestTags:["food","home"], styleFit:["aesthetic","practical"], occasionFit:["birthday","christmas","wedding","just_because"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:94, isPremium:false, inStock:true, categories:["food"] },

  // ── KNIHY ──
  { id:"p13", name:"Sapiens — Yuval Noah Harari (CZ)", description:"Bestseller o historii lidstva. Překlad do češtiny, brožovaná vazba.", price:399, originalUrl:"https://www.mall.cz/knihy/sapiens-harari", imageUrl:"/products/p13.svg", sourceShop:"Mall.cz", rating:4.8, genderFit:["male","female"], ageRange:["teen","young_adult","adult","senior"], interestTags:["books"], styleFit:["intellectual","practical"], occasionFit:["birthday","christmas","graduation","just_because"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:95, isPremium:false, inStock:true, categories:["books"] },
  { id:"p14", name:"Velká kniha českých receptů", description:"400 tradičních receptů s fotografiemi. Pevná vazba, dárková edice.", price:690, originalUrl:"https://www.mall.cz/knihy/velka-kniha-ceskych-receptu", imageUrl:"/products/p14.svg", sourceShop:"Mall.cz", rating:4.6, genderFit:["female","male"], ageRange:["adult","senior","elderly"], interestTags:["books","food"], styleFit:["practical","comfort"], occasionFit:["birthday","christmas","mothers_day","wedding"], giftType:"physical", isPersonalizable:false, isLocal:true, popularityScore:88, isPremium:false, inStock:true, categories:["books"] },
  { id:"p15", name:"Mindset — Carol Dweck (CZ)", description:"Kniha o růstovém myšlení. Jak změnit přístup k úspěchu a učení.", price:349, originalUrl:"https://www.mall.cz/knihy/mindset-dweck", imageUrl:"/products/p15.svg", sourceShop:"Mall.cz", rating:4.7, genderFit:["male","female"], ageRange:["teen","young_adult","adult"], interestTags:["books"], styleFit:["intellectual","practical"], occasionFit:["birthday","graduation","just_because"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:90, isPremium:false, inStock:true, categories:["books"] },

  // ── SPORT & OUTDOOR ──
  { id:"p16", name:"Termoska Stanley Classic 1L", description:"Ikonická nerezová termoska. Drží teplo 24h, chlad 120h. Doživotní záruka.", price:1190, originalUrl:"https://www.mall.cz/termosky/stanley-classic-1l", imageUrl:"/products/p16.svg", sourceShop:"Mall.cz", rating:4.9, genderFit:["male","female"], ageRange:["young_adult","adult","senior"], interestTags:["sport","food"], styleFit:["practical","adventurous"], occasionFit:["birthday","christmas","just_because"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:97, isPremium:false, inStock:true, categories:["sport"] },
  { id:"p17", name:"Čelovka Petzl Actik Core 600lm", description:"Nabíjecí čelovka s 600 lumeny. 3 světelné režimy, červené světlo.", price:1690, originalUrl:"https://www.mall.cz/celovky/petzl-actik-core", imageUrl:"/products/p17.svg", sourceShop:"Mall.cz", rating:4.8, genderFit:["male","female"], ageRange:["young_adult","adult","senior"], interestTags:["sport","tech"], styleFit:["adventurous","practical"], occasionFit:["birthday","christmas","just_because"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:91, isPremium:false, inStock:true, categories:["sport"] },
  { id:"p18", name:"Jógamatka Manduka eKO Lite 4mm", description:"Přírodní kaučuk, protiskluzový povrch. Ekologická výroba.", price:2290, originalUrl:"https://www.mall.cz/jogamatky/manduka-eko-lite", imageUrl:"/products/p18.svg", sourceShop:"Mall.cz", rating:4.7, genderFit:["female","male"], ageRange:["young_adult","adult","senior"], interestTags:["sport","wellness"], styleFit:["aesthetic","comfort"], occasionFit:["birthday","christmas","just_because"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:89, isPremium:false, inStock:true, categories:["sport"] },

  // ── DOMÁCNOST & DEKORACE ──
  { id:"p19", name:"Smaltovaná cedule s textem dle přání", description:"400×200mm cedule s vlastním textem. Tradiční česká smaltovna.", price:890, originalUrl:"https://www.darek.cz/smaltovana-cedule", imageUrl:"/products/p19.svg", sourceShop:"Darek.cz", rating:4.9, genderFit:["female","male"], ageRange:["young_adult","adult","senior","elderly"], interestTags:["home","crafts"], styleFit:["aesthetic","practical"], occasionFit:["birthday","christmas","wedding","valentine","just_because"], giftType:"physical", isPersonalizable:true, isLocal:true, popularityScore:98, isPremium:false, inStock:true, categories:["home"] },
  { id:"p20", name:"Rotující fotokostka s hodinami", description:"Dřevěná kostka pro 5 fotek 10×10cm. Analogové hodiny na vrchu.", price:438, originalUrl:"https://www.darek.cz/fotokostka", imageUrl:"/products/p20.svg", sourceShop:"Darek.cz", rating:5.0, genderFit:["female","male"], ageRange:["young_adult","adult","senior","elderly"], interestTags:["home","crafts"], styleFit:["comfort","aesthetic","sentimental"], occasionFit:["birthday","christmas","valentine","wedding","mothers_day"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:100, isPremium:false, inStock:true, categories:["home"] },
  { id:"p21", name:"Vonná svíčka Woodwick Fireside", description:"Praskající knot evokující oheň v krbu. Vůně santalové dřevo a amber.", price:690, originalUrl:"https://www.mall.cz/svicky/woodwick-fireside", imageUrl:"/products/p21.svg", sourceShop:"Mall.cz", rating:4.8, genderFit:["female","male"], ageRange:["young_adult","adult","senior"], interestTags:["home","wellness"], styleFit:["comfort","aesthetic"], occasionFit:["birthday","christmas","valentine","just_because"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:94, isPremium:false, inStock:true, categories:["home"] },

  // ── ZÁŽITKY & POUKAZY ──
  { id:"p22", name:"Degustace vín pro dva — Valtice", description:"2h řízená degustace 8 vín v historických sklepech. Sommeliér + občerstvení.", price:1990, originalUrl:"https://www.mall.cz/zazitky/degustace-vin-valtice", imageUrl:"/products/p22.svg", sourceShop:"Mall.cz", rating:4.9, genderFit:["male","female"], ageRange:["young_adult","adult","senior"], interestTags:["experiences","food"], styleFit:["aesthetic","intellectual","adventurous"], occasionFit:["birthday","valentine","wedding","just_because"], giftType:"experience", isPersonalizable:false, isLocal:true, popularityScore:97, isPremium:false, inStock:true, categories:["experiences"] },
  { id:"p23", name:"Tandemový seskok padákem", description:"Volný pád z 4000m s instruktorem. Lokace po celé ČR.", price:4490, originalUrl:"https://www.mall.cz/zazitky/tandemovy-seskok", imageUrl:"/products/p23.svg", sourceShop:"Mall.cz", rating:4.8, genderFit:["male","female"], ageRange:["young_adult","adult"], interestTags:["experiences","sport"], styleFit:["adventurous"], occasionFit:["birthday","graduation","just_because"], giftType:"experience", isPersonalizable:false, isLocal:true, popularityScore:95, isPremium:false, inStock:true, categories:["experiences"] },
  { id:"p24", name:"Wellness pobyt pro dva — 2 noci", description:"Hotel s wellness, polopenze a masáží pro dva. Jižní Morava.", price:4990, originalUrl:"https://www.mall.cz/zazitky/wellness-pobyt", imageUrl:"/products/p24.svg", sourceShop:"Mall.cz", rating:4.7, genderFit:["male","female"], ageRange:["adult","senior"], interestTags:["experiences","wellness"], styleFit:["comfort","aesthetic"], occasionFit:["birthday","valentine","mothers_day","wedding"], giftType:"experience", isPersonalizable:false, isLocal:true, popularityScore:93, isPremium:true, inStock:true, categories:["experiences"] },

  // ── HRY & ZÁBAVA ──
  { id:"p25", name:"Interaktivní glóbus Albi — Kouzelné čtení", description:"Mluvicí glóbus s interaktivním perem. 1000+ informací o zemích.", price:1714, originalUrl:"https://www.darek.cz/globus-albi", imageUrl:"/products/p25.svg", sourceShop:"Darek.cz", rating:5.0, genderFit:["female","male"], ageRange:["school","preschool"], interestTags:["books","games","tech"], styleFit:["intellectual","adventurous"], occasionFit:["birthday","christmas","graduation"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:100, isPremium:false, inStock:true, categories:["games"] },
  { id:"p26", name:"Desková hra Wingspan (Křídla) CZ", description:"Oceňovaná strategická hra o ptácích. 1–5 hráčů, 45–70 min.", price:1290, originalUrl:"https://www.mall.cz/deskove-hry/wingspan-cz", imageUrl:"/products/p26.svg", sourceShop:"Mall.cz", rating:4.9, genderFit:["male","female"], ageRange:["teen","young_adult","adult","senior"], interestTags:["games","books"], styleFit:["intellectual","comfort"], occasionFit:["birthday","christmas","just_because"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:96, isPremium:false, inStock:true, categories:["games"] },
  { id:"p27", name:"LEGO Architecture Eiffelova věž", description:"10307 — 10 001 dílků, výška 149cm. Sběratelský set pro dospělé.", price:4999, originalUrl:"https://www.mall.cz/lego/architecture-eiffelova-vez", imageUrl:"/products/p27.svg", sourceShop:"Mall.cz", rating:4.9, genderFit:["male","female"], ageRange:["young_adult","adult"], interestTags:["games","crafts","home"], styleFit:["aesthetic","intellectual"], occasionFit:["birthday","christmas","valentine"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:98, isPremium:true, inStock:true, categories:["games"] },
  { id:"p28", name:"Antigravitační autíčko Wall Climber", description:"RC auto jezdící po stěnách a stropě. Infrared ovládání.", price:485, originalUrl:"https://www.darek.cz/wall-climber", imageUrl:"/products/p28.svg", sourceShop:"Darek.cz", rating:4.5, genderFit:["male","female"], ageRange:["school","preschool"], interestTags:["tech","games"], styleFit:["adventurous","practical"], occasionFit:["birthday","christmas","just_because"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:90, isPremium:false, inStock:true, categories:["games"] },

  // ── MÓDNÍ DOPLŇKY & ŠPERKY ──
  { id:"p29", name:"Elegantní stříbrná souprava Srdce", description:"Náhrdelník + náušnice ze stříbra 925 s kubickým zirkonem.", price:1185, originalUrl:"https://www.darek.cz/stribrna-souprava-srdce", imageUrl:"/products/p29.svg", sourceShop:"Darek.cz", rating:4.9, genderFit:["female"], ageRange:["teen","young_adult","adult","senior"], interestTags:["fashion","premium"], styleFit:["aesthetic","comfort"], occasionFit:["birthday","christmas","valentine","wedding","mothers_day"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:98, isPremium:false, inStock:true, categories:["fashion"] },
  { id:"p30", name:"Parker Royal I.M. Black GT — pero s gravírováním", description:"Kuličkové pero s vlastním textem. Dárková kazeta.", price:890, originalUrl:"https://www.darek.cz/parker-royal", imageUrl:"/products/p30.svg", sourceShop:"Darek.cz", rating:4.9, genderFit:["male","female"], ageRange:["young_adult","adult","senior"], interestTags:["crafts","books","premium"], styleFit:["aesthetic","practical","intellectual"], occasionFit:["birthday","graduation","christmas","wedding"], giftType:"physical", isPersonalizable:true, isLocal:false, popularityScore:98, isPremium:false, inStock:true, categories:["fashion"] },
  { id:"p31", name:"Kožený opasek ruční výroby — Kůže z Vysočiny", description:"Hovězí kůže, ruční steh, mosazná spona. Každý kus originál.", price:1490, originalUrl:"https://www.mall.cz/opasky/kuze-z-vysociny", imageUrl:"/products/p31.svg", sourceShop:"Mall.cz", rating:4.8, genderFit:["male"], ageRange:["young_adult","adult","senior"], interestTags:["fashion","crafts"], styleFit:["aesthetic","practical"], occasionFit:["birthday","christmas","valentine"], giftType:"physical", isPersonalizable:true, isLocal:true, popularityScore:92, isPremium:false, inStock:true, categories:["fashion"] },
  { id:"p32", name:"Hedvábný šátek — české sklo motiv", description:"100% hedvábí, potisk inspirovaný českým křišťálem. 90×90cm.", price:1890, originalUrl:"https://www.mall.cz/satky/hedvabny-ceske-sklo", imageUrl:"/products/p32.svg", sourceShop:"Mall.cz", rating:4.7, genderFit:["female"], ageRange:["adult","senior","elderly"], interestTags:["fashion","crafts"], styleFit:["aesthetic","comfort"], occasionFit:["birthday","christmas","mothers_day","valentine"], giftType:"physical", isPersonalizable:false, isLocal:true, popularityScore:89, isPremium:false, inStock:true, categories:["fashion"] },

  // ── PRO DĚTI ──
  { id:"p33", name:"Pokladnička Krtek — kovová retro kasička", description:"Plechová kasička s motivem Krtečka. Retro design, české zpracování.", price:158, originalUrl:"https://www.darek.cz/pokladnicka-krtek", imageUrl:"/products/p33.svg", sourceShop:"Darek.cz", rating:4.8, genderFit:["female","male"], ageRange:["baby","preschool","school"], interestTags:["home","crafts"], styleFit:["practical","comfort"], occasionFit:["birthday","christmas","just_because"], giftType:"physical", isPersonalizable:false, isLocal:true, popularityScore:96, isPremium:false, inStock:true, categories:["kids"] },
  { id:"p34", name:"Dětské tričko Lightning REX — svítí ve tmě", description:"100% bavlna, potisk dinosaura svítícího ve tmě. Velikosti 104–152.", price:665, originalUrl:"https://www.darek.cz/tricko-rex", imageUrl:"/products/p34.svg", sourceShop:"Darek.cz", rating:4.6, genderFit:["male","female"], ageRange:["preschool","school"], interestTags:["fashion","games"], styleFit:["adventurous","comfort"], occasionFit:["birthday","christmas","just_because"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:92, isPremium:false, inStock:true, categories:["kids"] },
  { id:"p35", name:"Magnetická tabule — set 120 dílků", description:"Dřevěná tabule 2v1 (křída + magnety). Zvířátka, čísla, písmena.", price:549, originalUrl:"https://www.mall.cz/hracky/magneticka-tabule-set", imageUrl:"/products/p35.svg", sourceShop:"Mall.cz", rating:4.7, genderFit:["female","male"], ageRange:["preschool","school"], interestTags:["games","crafts","books"], styleFit:["intellectual","practical"], occasionFit:["birthday","christmas"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:91, isPremium:false, inStock:true, categories:["kids"] },
  { id:"p36", name:"Dětský batoh Skip Hop Zoo — Lištička", description:"Ergonomický batůžek pro předškoláky. Izolovaná kapsa na svačinu.", price:699, originalUrl:"https://www.mall.cz/batohy/skip-hop-zoo-listka", imageUrl:"/products/p36.svg", sourceShop:"Mall.cz", rating:4.8, genderFit:["female","male"], ageRange:["preschool","school"], interestTags:["sport","pets"], styleFit:["practical","comfort"], occasionFit:["birthday","christmas","just_because"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:93, isPremium:false, inStock:true, categories:["kids"] },

  // ── DALŠÍ ──
  { id:"p37", name:"Pantofle Kravička — protiskluzové", description:"Plyšové pantofle s motivem kravičky. Velikosti 36–42. Protiskluz.", price:395, originalUrl:"https://www.darek.cz/pantofle-kravicka", imageUrl:"/products/p37.svg", sourceShop:"Darek.cz", rating:4.8, genderFit:["female","male"], ageRange:["young_adult","adult","senior","elderly"], interestTags:["wellness","home","pets"], styleFit:["comfort","aesthetic"], occasionFit:["birthday","christmas","just_because","mothers_day"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:96, isPremium:false, inStock:true, categories:["home"] },
  { id:"p38", name:"Termohrnek Yorkshire Terrier", description:"Designový termohrnek 350ml s motivem Yorkšíra. Nerez, dvojitá stěna.", price:495, originalUrl:"https://www.darek.cz/termohrnek-yorkie", imageUrl:"/products/p38.svg", sourceShop:"Darek.cz", rating:4.7, genderFit:["female","male"], ageRange:["young_adult","adult","senior"], interestTags:["pets","food"], styleFit:["comfort","aesthetic"], occasionFit:["birthday","christmas","just_because"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:94, isPremium:false, inStock:true, categories:["pets"] },
  { id:"p39", name:"Stojánek na brýle — polyresinový designový", description:"Vtipný stojánek ve tvaru obličeje. Polyresin, výška 14cm.", price:99, originalUrl:"https://www.darek.cz/stojanek-bryle", imageUrl:"/products/p39.svg", sourceShop:"Darek.cz", rating:4.5, genderFit:["female","male"], ageRange:["adult","senior","elderly"], interestTags:["home"], styleFit:["practical","comfort"], occasionFit:["birthday","christmas","just_because"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:90, isPremium:false, inStock:true, categories:["home"] },
  { id:"p40", name:"Čajová souprava Japandi — termoizolační", description:"Porcelánový set konvice + 2 šálky v japonsko-skandinávském stylu.", price:985, originalUrl:"https://www.darek.cz/cajova-souprava-japandi", imageUrl:"/products/p40.svg", sourceShop:"Darek.cz", rating:4.7, genderFit:["female","male"], ageRange:["young_adult","adult","senior"], interestTags:["food","home"], styleFit:["aesthetic","intellectual"], occasionFit:["birthday","christmas","wedding","just_because"], giftType:"physical", isPersonalizable:false, isLocal:false, popularityScore:94, isPremium:false, inStock:true, categories:["food"] },
]
