import { QuizQuestion } from '@/types'

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'relationship',
    title: 'Pro koho hledáte dárek?',
    subtitle: 'Vztah ovlivňuje tón i typ doporučení',
    type: 'single',
    options: [
      { value: 'partner',   label: 'Partner / Partnerka', emoji: '💑', description: 'Romantické, osobní' },
      { value: 'parent',    label: 'Maminka / Tatínek',   emoji: '👨‍👩‍👧', description: 'Sentimentální, kvalitní' },
      { value: 'friend',    label: 'Kamarád / Kamarádka', emoji: '🤝', description: 'Zábavné, originální' },
      { value: 'sibling',   label: 'Sourozenec',          emoji: '👫', description: 'Osobní, sdílené zájmy' },
      { value: 'colleague', label: 'Kolega / Kolegyně',   emoji: '💼', description: 'Neutrální, profesionální' },
      { value: 'child',     label: 'Dítě',                emoji: '🧒', description: 'Hravé, vzdělávací' },
      { value: 'self',      label: 'Pro sebe',            emoji: '✨', description: 'Sebeodměna' },
      { value: 'pet',       label: 'Domácí mazlíček',     emoji: '🐾', description: 'Pes, kočka, králík...' },
    ],
  },
  {
    id: 'ageGroup',
    title: 'Kolik je obdarovanému let?',
    subtitle: 'Věk je klíčový filtr',
    type: 'single',
    options: [
      { value: 'baby',        label: '0–2 roky',    emoji: '👶' },
      { value: 'preschool',   label: '3–5 let',     emoji: '🎨' },
      { value: 'school',      label: '6–12 let',    emoji: '📚' },
      { value: 'teen',        label: '13–18 let',   emoji: '🎮' },
      { value: 'young_adult', label: '19–30 let',   emoji: '🚀' },
      { value: 'adult',       label: '31–50 let',   emoji: '💎' },
      { value: 'senior',      label: '51–70 let',   emoji: '🌿' },
      { value: 'elderly',     label: '70+ let',     emoji: '☕' },
    ],
  },
  {
    id: 'gender',
    title: 'Je to pro ženu nebo muže?',
    type: 'single',
    options: [
      { value: 'female',  label: 'Žena / Dívka',  emoji: '👩' },
      { value: 'male',    label: 'Muž / Chlapec',  emoji: '👨' },
      { value: 'neutral', label: 'Nevím',           emoji: '🤷' },
    ],
  },
  {
    id: 'occasion',
    title: 'K jaké příležitosti?',
    type: 'single',
    options: [
      { value: 'birthday',    label: 'Narozeniny',         emoji: '🎂' },
      { value: 'christmas',   label: 'Vánoce / Svátky',    emoji: '🎄' },
      { value: 'nameday',     label: 'Svátek',             emoji: '📅' },
      { value: 'valentine',   label: 'Valentýn / Výročí',  emoji: '💝' },
      { value: 'mothers_day', label: 'Den matek / otců',   emoji: '🌷' },
      { value: 'wedding',     label: 'Svatba / Zásnuby',   emoji: '💍' },
      { value: 'graduation',  label: 'Promoce / Úspěch',   emoji: '🎓' },
      { value: 'just_because',label: 'Jen tak, pro radost', emoji: '🌟' },
    ],
  },
  {
    id: 'interests',
    title: 'Jaké jsou zájmy obdarovaného?',
    subtitle: 'Vyberte 1–3 oblasti',
    type: 'multi',
    maxSelections: 3,
    options: [
      { value: 'tech',        label: 'Technologie & Gadgety', emoji: '📱' },
      { value: 'sport',       label: 'Sport & Outdoor',       emoji: '⚽' },
      { value: 'fashion',     label: 'Móda & Krása',          emoji: '👗' },
      { value: 'home',        label: 'Domácnost & Bydlení',   emoji: '🏠' },
      { value: 'food',        label: 'Jídlo & Pití',          emoji: '🍷' },
      { value: 'books',       label: 'Knihy & Vzdělávání',    emoji: '📖' },
      { value: 'games',       label: 'Hry & Zábava',          emoji: '🎲' },
      { value: 'experiences', label: 'Zážitky & Cestování',   emoji: '✈️' },
      { value: 'crafts',      label: 'Tvoření & Ruční práce', emoji: '🎨' },
      { value: 'wellness',    label: 'Zdraví & Wellness',     emoji: '🧘' },
      { value: 'pets',        label: 'Zvířata',               emoji: '🐾' },
      { value: 'unknown',     label: 'Nevím',                 emoji: '🎁' },
    ],
  },
  {
    id: 'giftType',
    title: 'Jaký typ dárku hledáte?',
    type: 'single',
    options: [
      { value: 'physical',   label: 'Fyzický dárek',    emoji: '📦', description: 'Něco hmatatelného' },
      { value: 'experience', label: 'Poukaz / Zážitek', emoji: '🎟️', description: 'Nezapomenutelný moment' },
      { value: 'both',       label: 'Oboje',            emoji: '✨', description: 'Ukažte mi vše' },
    ],
  },
  {
    id: 'style',
    title: 'Co by ho/ji nejvíc potěšilo?',
    subtitle: 'Jaký typ dárku hledáte',
    type: 'single',
    options: [
      { value: 'practical',     label: 'Něco užitečného',    emoji: '🔧', description: 'Praktické věci do života' },
      { value: 'aesthetic',     label: 'Něco krásného',       emoji: '🎨', description: 'Design, šperky, dekorace' },
      { value: 'adventurous',   label: 'Něco zábavného',     emoji: '😄', description: 'Vtipné, originální, překvapivé' },
      { value: 'food_drink',    label: 'Něco k jídlu/pití',  emoji: '🍷', description: 'Delikatesy, víno, čokoláda' },
      { value: 'comfort',       label: 'Něco osobního',      emoji: '✨', description: 'Na míru, s věnováním' },
      { value: 'any_style',     label: 'Nevím',              emoji: '🌈', description: 'Ukažte mi vše' },
    ],
  },
  {
    id: 'budget',
    title: 'Jaký je váš rozpočet?',
    subtitle: 'Zobrazíme dárky ve vámi zvoleném rozmezí',
    type: 'single',
    options: [
      { value: 'max300',          label: 'Do 300 Kč',        emoji: '💰' },
      { value: 'range300_500',    label: '300–500 Kč',       emoji: '💰' },
      { value: 'range500_1000',   label: '500–1 000 Kč',     emoji: '💳' },
      { value: 'range1000_2000',  label: '1 000–2 000 Kč',   emoji: '💳' },
      { value: 'range2000_5000',  label: '2 000–5 000 Kč',   emoji: '💎' },
      { value: 'unlimited',       label: 'Bez omezení',      emoji: '👑' },
      { value: 'custom',          label: 'Vlastní rozsah',   emoji: '✏️', description: 'Nastavte si min a max cenu' },
    ],
  },
]
