import { QuizQuestion } from '@/types'

export const QUESTIONS: QuizQuestion[] = [
  {
    id: "relationship",
    title: "Pro koho dárek vybíráte?",
    subtitle: "Ovlivní tón i typ doporučení",
    multi: false,
    options: [
      { label: "Pro partnera/ku", key: "partner", icon: "💕" },
      { label: "Pro maminku / tatínka", key: "parent", icon: "🏠" },
      { label: "Pro kamaráda/ku", key: "friend", icon: "🎉" },
      { label: "Pro sourozence", key: "sibling", icon: "👫" },
      { label: "Pro kolegu/kolegyni", key: "colleague", icon: "💼" },
      { label: "Pro dítě", key: "child", icon: "🧸" },
      { label: "Pro sebe", key: "self", icon: "🎁" },
    ],
  },
  {
    id: "ageGroup",
    title: "Kolik je obdarovanému let?",
    subtitle: "Pomůže nám vybrat věkově vhodný dárek",
    multi: false,
    options: [
      { label: "0–2 roky", key: "baby", icon: "👶" },
      { label: "3–5 let", key: "preschool", icon: "🧒" },
      { label: "6–12 let", key: "school", icon: "🎒" },
      { label: "13–18 let", key: "teen", icon: "🎮" },
      { label: "19–30 let", key: "young_adult", icon: "🧑" },
      { label: "31–50 let", key: "adult", icon: "👨‍💻" },
      { label: "51–70 let", key: "senior", icon: "👴" },
      { label: "70+ let", key: "elderly", icon: "🤍" },
    ],
  },
  {
    id: "gender",
    title: "Je to pro ženu nebo muže?",
    subtitle: "Pomůže filtrovat produktové kategorie",
    multi: false,
    options: [
      { label: "Žena / Dívka", key: "female", icon: "♀" },
      { label: "Muž / Chlapec", key: "male", icon: "♂" },
      { label: "Nebinární / Nechci specifikovat", key: "neutral", icon: "⚪" },
    ],
  },
  {
    id: "occasion",
    title: "K jaké příležitosti?",
    subtitle: "Kontext nákupu ovlivní výběr",
    multi: false,
    options: [
      { label: "Narozeniny", key: "birthday", icon: "🎂" },
      { label: "Vánoce / Svátky", key: "christmas", icon: "🎄" },
      { label: "Valentýn / Výročí", key: "valentine", icon: "❤️" },
      { label: "Den matek / Den otců", key: "mothers_day", icon: "🌷" },
      { label: "Svatba / Zásnuby", key: "wedding", icon: "💍" },
      { label: "Promoce / Úspěch", key: "graduation", icon: "🎓" },
      { label: "Jen tak, pro radost", key: "just_because", icon: "✨" },
    ],
  },
  {
    id: "interests",
    title: "Jaké jsou zájmy obdarovaného?",
    subtitle: "Vyberte 1–3 možnosti",
    multi: true,
    maxSelect: 3,
    options: [
      { label: "Technologie & Gadgety", key: "tech", icon: "📱" },
      { label: "Sport & Outdoor", key: "sport", icon: "⚽" },
      { label: "Móda & Krása", key: "fashion", icon: "👗" },
      { label: "Domácnost & Bydlení", key: "home", icon: "🏡" },
      { label: "Jídlo & Pití", key: "food", icon: "🍷" },
      { label: "Knihy & Vzdělávání", key: "books", icon: "📚" },
      { label: "Hry & Zábava", key: "games", icon: "🎲" },
      { label: "Zážitky & Cestování", key: "experiences", icon: "✈️" },
      { label: "Tvoření & Ruční práce", key: "crafts", icon: "🎨" },
      { label: "Zdraví & Wellness", key: "wellness", icon: "🧘" },
      { label: "Zvířata", key: "pets", icon: "🐾" },
      { label: "Nevím", key: "unknown", icon: "❓" },
    ],
  },
  {
    id: "giftType",
    title: "Jaký typ dárku hledáte?",
    subtitle: "Fyzický produkt nebo zážitek?",
    multi: false,
    options: [
      { label: "Fyzický dárek", key: "physical", icon: "📦" },
      { label: "Zážitek / Poukaz", key: "experience", icon: "🎟️" },
      { label: "Obě možnosti", key: "both", icon: "🎁" },
    ],
  },
  {
    id: "style",
    title: "Jaký styl / osobnost obdarovaného?",
    subtitle: "Emocionální profilování",
    multi: false,
    options: [
      { label: "Praktik – oceňuje užitečné", key: "practical", icon: "🔧" },
      { label: "Dobrodruh/ka – miluje zážitky", key: "adventurous", icon: "🏔️" },
      { label: "Estét/ka – záleží na designu", key: "aesthetic", icon: "💎" },
      { label: "Intelektuál/ka – rád/a se učí", key: "intellectual", icon: "🧠" },
      { label: "Pohodář/ka – užívá si komfort", key: "comfort", icon: "🛋️" },
      { label: "Nevím", key: "any_style", icon: "🤷" },
    ],
  },
  {
    id: "budget",
    title: "Jaký máte rozpočet?",
    subtitle: "Zobrazíme produkty do zvoleného stropu",
    multi: false,
    options: [
      { label: "Do 300 Kč", key: "max300", icon: "💰" },
      { label: "Do 500 Kč", key: "max500", icon: "💰" },
      { label: "Do 1 000 Kč", key: "max1000", icon: "💰" },
      { label: "Do 2 000 Kč", key: "max2000", icon: "💰" },
      { label: "Do 5 000 Kč", key: "max5000", icon: "💰" },
      { label: "Nezáleží na ceně", key: "unlimited", icon: "💎" },
    ],
  },
]
